name: Build and Publish

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build ViT-H image
        uses: docker/build-push-action@v4
        with:
          # relative path to the place where source code with Dockerfile is located
          context: .
          # Note: tags has to be all lower-case
          tags: |
            matteopic/segment-anything:latest
            matteopic/segment-anything:sam_vit_h
            matteopic/segment-anything:sam_vit_h_4b8939
            matteopic/segment-anything:${{ env.RELEASE_VERSION }}-sam_vit_h_4b8939
          # build on feature branches, push only on main branch
          push: true
          build-args: |
            MODEL_CHECKPOINT=sam_vit_h_4b8939

      - name: Build ViT-L image
        uses: docker/build-push-action@v4
        with:
          # relative path to the place where source code with Dockerfile is located
          context: .
          # Note: tags has to be all lower-case
          tags: |
            matteopic/segment-anything:latest
            matteopic/segment-anything:sam_vit_l
            matteopic/segment-anything:sam_vit_l_0b3195
            matteopic/segment-anything:${{ env.RELEASE_VERSION }}-sam_vit_l_0b3195
          # build on feature branches, push only on main branch
          push: true
          build-args: |
            MODEL_CHECKPOINT=sam_vit_l_0b3195

      - name: Build ViT-B image
        uses: docker/build-push-action@v4
        with:
          # relative path to the place where source code with Dockerfile is located
          context: .
          # Note: tags has to be all lower-case
          tags: |
            matteopic/segment-anything:latest
            matteopic/segment-anything:sam_vit_b
            matteopic/segment-anything:sam_vit_b_01ec64
            matteopic/segment-anything:${{ env.RELEASE_VERSION }}-sam_vit_b_01ec64
          # build on feature branches, push only on main branch
          push: true
          build-args: |
            MODEL_CHECKPOINT=sam_vit_b_01ec64

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}